{
  "exact": {
    "ニュース": "News",
    "ニュース・気象情報": "News and Weather",
    "気象情報": "Weather Information",
    "ＮＨＫニュース７": "NHK News 7",
    "首都圏ネットワーク": "Shutoken Network",
    "首都圏ニュース８４５": "Shutoken News 845",
    "列島ニュース": "News from Around Japan",
    "あさイチ": "Asaichi",
    "みんなの体操": "Minna no Taiso",
    "テレビ体操": "TV Taiso",
    "みんなのうた": "Minna no Uta",
    "時論公論": "Jiron Koron",
    "大相撲": "Grand Sumo",
    "ブラタモリ": "Buratamori",
    "チコちゃんに叱られる！": "Chico Will Scold You!",
    "ドキュメント７２時間": "Document 72 Hours",
    "ニュースウオッチ９": "News Watch 9",
    "サタデーウオッチ９": "Saturday Watch 9",
    "ダーウィンが来た！": "Darwin's Amazing Animals",
    "小さな旅": "A Small Journey",
    "名曲アルバム": "Masterpiece Album",
    "新プロジェクトＸ": "Project X: Challengers",
    "ファミリーヒストリー": "Family History",
    "国際報道": "International News Report",
    "おはよう日本": "Good Morning Japan",
    "ＮＨＫニュース　おはよう日本": "NHK News: Good Morning Japan",
    "ＮＨＫニュース　おはよう首都圏": "NHK News: Good Morning Shutoken",
    "連続テレビ小説": "Serial TV Novel",
    "豊臣兄弟！": "Toyotomi Brothers!",
    "大河ドラマ": "Taiga Drama",
    "ＮＨＫスペシャル": "NHK Special",
    "風、薫る": "Kaze, Kaoru",
    "ひよっこ": "Hiyokko",
    "ブラッサム": "Blossom"
  },
  "prefix": {
    "ＮＨＫニュース７": "NHK News 7",
    "首都圏ネットワーク": "Shutoken Network",
    "首都圏ニュース８４５": "Shutoken News 845",
    "ＮＨＫニュース　おはよう日本": "NHK News: Good Morning Japan",
    "ＮＨＫニュース　おはよう首都圏": "NHK News: Good Morning Shutoken",
    "ニュースウオッチ９": "News Watch 9",
    "サタデーウオッチ９": "Saturday Watch 9",
    "大相撲": "Grand Sumo",
    "ブラタモリ": "Buratamori",
    "チコちゃんに叱られる！": "Chico Will Scold You!",
    "ドキュメント７２時間": "Document 72 Hours",
    "ダーウィンが来た！": "Darwin's Amazing Animals",
    "小さな旅": "A Small Journey",
    "時論公論": "Jiron Koron",
    "列島ニュース": "News from Around Japan",
    "あさイチ": "Asaichi",
    "みんなのうた": "Minna no Uta",
    "名曲アルバム": "Masterpiece Album",
    "新プロジェクトＸ": "Project X: Challengers",
    "ファミリーヒストリー": "Family History",
    "国際報道": "International News Report",
    "【連続テレビ小説】": "Serial TV Novel: ",
    "連続テレビ小説": "Serial TV Novel",
    "大河ドラマ": "Taiga Drama",
    "ＮＨＫスペシャル": "NHK Special"
  }
}
